#!/bin/bash
# Configuración centralizada de claude-session-topics
# Usage: source scripts/lib/config.sh

# Paths
CLAUDE_DIR="${HOME}/.claude"
TOPICS_DIR="${CLAUDE_DIR}/session-topics"
SETTINGS_FILE="${CLAUDE_DIR}/settings.json"
SKILLS_DIR="${CLAUDE_DIR}/skills"

# Límites
MAX_TOPIC_LENGTH=50
MAX_SET_TOPIC_LENGTH=100
STALE_DAYS=7

# Colores ANSI
COLOR_RED='\033[31m'
COLOR_GREEN='\033[32m'
COLOR_YELLOW='\033[33m'
COLOR_BLUE='\033[34m'
COLOR_MAGENTA='\033[35m'
COLOR_CYAN='\033[36m'
COLOR_WHITE='\033[37m'
COLOR_ORANGE='\033[38;5;208m'
COLOR_GREY='\033[90m'
COLOR_BOLD='\033[1m'
COLOR_RESET='\033[0m'

# Exportar para uso en otros scripts
export CLAUDE_DIR TOPICS_DIR SETTINGS_FILE SKILLS_DIR
export MAX_TOPIC_LENGTH MAX_SET_TOPIC_LENGTH STALE_DAYS
export COLOR_RED COLOR_GREEN COLOR_YELLOW COLOR_BLUE
export COLOR_MAGENTA COLOR_CYAN COLOR_WHITE COLOR_ORANGE COLOR_GREY
export COLOR_BOLD COLOR_RESET
